### PR TITLE
chore(database-setup)This sets up the postgres database[#165157731]

### PR DESCRIPTION
**Pull request by engjames**
**What does this PR do?**
-Sets up the postgres database
**Description of the task**
After cloning this repository,  create a virtual environment 
-Activate the virtual environment i.e. source env/bin/activate
- Install packages in the virtual environment using pip3 install -r requirements.txt
- Install psycopg2 driver to use postgres i.e pip3 install psycopg2
-Run the environment variables in the terminal i.e export DB_NAME=inn_db
- Run the migrations using python3 manage.py runserver . 
-Tables will be created if the database was created.
@mwinel @3Nakajugo @sanya-kenneth @KabohaJeanMark @@PatrickMugayaJoel

Please kindly review and give ASK feedback. Don't attack.. just kidding!

### CODE REVIEW

**Review by PatrickMugayaJoel — APPROVED** [review]

**Comment by PatrickMugayaJoel** [comment]
The installation instructions in this PR, I would not mind seeing them in the readme as well

**Comment by mwinel** [comment]
@3Nakajugo is responsible for the readme.

**Comment by 3Nakajugo** [comment]
@engjames if you could add a link to the relevent PT story . it makes it easier to know which task has been completed.
### What are the relevant pivotal tracker stories? 

 other wise great job.

**Comment by sanya-kenneth** [comment]
great work @engjames

**Pull request merged**
